version: "3"
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:old
    restart: always
    volumes:
      - "/nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    network_mode: host
